{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="row">

<form action={concat($module.functions.password.uri,"/",$userID)|ezurl} method="post" name="Password">

    <div class="col-md-8 col-md-offset-2">
      
        <h1>Cambia la password!</h1>    
        
        {if $message}
            {if or($oldPasswordNotValid,$newPasswordNotMatch,$newPasswordNotValidate,$newPasswordMustDiffer)}
                {if $oldPasswordNotValid}
                    <div class="warning">
                        <h2>Reinserisci la vecchia password</h2>
                    </div>
                {/if}
                {if $newPasswordNotMatch}
                    <div class="warning">
                        <h2>Controlla le nuove password perché non corrsipondono</h2>
                    </div>
                {/if}
                {if $newPasswordNotValidate}
                    <div class="warning">
                        <h2>Password non valida</h2>
                    </div>
                {/if}
                {if $newPasswordMustDiffer}
                    <div class="warning">
                        <h2>La nuova password deve essere diversa dalla vecchia</h2>
                    </div>
                {/if}                    
            {else}
                <div class="feedback">
                    <h2>{'Password successfully updated.'|i18n('mbpaex/userpaex')}</h2>
                </div>
            {/if}
        {/if}
    
    
        {if $oldPasswordNotValid}*{/if}
        <label>Vecchia password</label>
        <input type="password" class="form-control" name="oldPassword" size="11" value="{$oldPassword}" />        
        
        <hr />
    
      <div class="row">
          <div class="col-md-6">
              {if or($newPasswordNotMatch,$newPasswordNotValidate)}*{/if}
              <label>Nuova password</label>
              <input type="password" class="form-control" name="newPassword" size="11" value="{$newPassword}" />              
          </div>
          <div class="col-md-6">
              {if or($newPasswordNotMatch,$newPasswordNotValidate)}*{/if}
              <label>Ridigita la nuova password</label>
              <input type="password" class="form-control" name="confirmPassword" size="11" value="{$confirmPassword}" />
              
          </div>          
      </div>

      <hr />
    
      <div class="buttonblock">
          <input class="button pull-left" type="submit" name="CancelButton" value="Annulla" />
          <input class="defaultbutton pull-right" type="submit" name="OKButton" value="{'OK'|i18n('mbpaex/userpaex')}" />          
      </div>
    
    </div>


</form>

</div>
