{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $class = cond( $object_parameters.align, concat( ' class="embed-inline-', $object_parameters.align, '"' ), '' )}
{if $object.main_node_id|null|not}
    {def $openpa = object_handler($object.main_node)}
    <a href="{$openpa.content_link.full_link}">{$object.name|wash}</a>
    {undef $openpa}
{else}
    {if $class}<span{$class}>{/if}{$object.name|wash}{if $class}</span>{/if}
{/if}
