{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=utf8?*}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{$site.http_equiv.Content-language|wash}" lang="{$site.http_equiv.Content-language|wash}">

<head>

  {include uri='design:page_head_script.tpl'}
  {include uri='design:page_head_style.tpl'}  

  <link rel="stylesheet" type="text/css" href={"stylesheets/print.css"|ezdesign} />


</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><a href={"/"|ezurl} title="{ezini('SiteSettings','SiteName')}">{ezini('SiteSettings','SiteName')}</a></h1>        
      </div>      
    </div>
    
    {include uri="design:page_mainarea.tpl"}
    
  </div>


<!--DEBUG_REPORT-->

</body>
</html>
